# Generated by Django 3.0.8 on 2021-04-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume1', '0002_auto_20210408_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='experience',
            field=models.CharField(choices=[('less then one year', '1'), ('between two and three years', '3'), ('between three and five years', '5'), ('between five and ten years', '7'), ('more then ten years', '10')], max_length=50, null=True),
        ),
    ]
