# Generated by Django 3.0.8 on 2021-04-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume1', '0003_auto_20210408_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='importance',
            field=models.CharField(choices=[('REQUIRED', '1'), ('SECONDARY', '2'), ('PLUS', '3')], max_length=20),
        ),
    ]
