# Generated by Django 3.0.8 on 2021-04-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume1', '0004_auto_20210408_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='importance',
            field=models.IntegerField(choices=[('REQUIRED', '1'), ('SECONDARY', '2'), ('PLUS', '3')], default=1),
        ),
    ]
