# Generated by Django 3.0.8 on 2021-04-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume1', '0006_auto_20210409_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp',
            name='date_created',
        ),
        migrations.AddField(
            model_name='apply',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
